name: Publish NPM Package

on:
  release:
    types: [published]

env:
  ALLOWED_PUBLISHER: hsubebe89

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Verify publisher authorization
        run: |
          if [ "${{ github.actor }}" != "${{ env.ALLOWED_PUBLISHER }}" ]; then
            echo "❌ ERROR: Only ${{ env.ALLOWED_PUBLISHER }} can publish to NPM"
            echo "Current actor: ${{ github.actor }}"
            exit 1
          fi
          echo "✅ Publisher authorization verified for ${{ github.actor }}"
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test:ci
        env:
          NODE_ENV: 'test'
          CI: 'true'
          
      - name: Build package
        run: npm run build
        
      - name: Update package version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current package version: $CURRENT_VERSION"
          echo "Target version: $VERSION"
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            echo "Updating package version to: $VERSION"
            npm version $VERSION --no-git-tag-version
          else
            echo "Version already matches target, skipping version update"
          fi
          
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}